import { chromium } from 'playwright'
import { execSync } from 'child_process'
const cookieStr = execSync(`cd /private/tmp/claude-501/-Users-marino/240b3dc8-f2e8-4dac-904f-68a79300cc05/scratchpad && python3 -c "import sys;sys.path.insert(0,'.');import lyft_api as C;print(C.cookies())"`).toString().trim()
const cookies = cookieStr.split('; ').map(p => { const i=p.indexOf('='); return { name:p.slice(0,i), value:p.slice(i+1), domain:'lyftai.io', path:'/' } })
const b = await chromium.launch(); const ctx = await b.newContext({ viewport:{width:1600,height:1100} })
await ctx.addCookies(cookies); const page = await ctx.newPage()
const bad = [], calls = []
page.on('response', r => { if (r.url().includes('/api/') && r.status() >= 400) bad.push(`${r.status()} ${r.url().replace('https://lyftai.io','').slice(0,70)}`) })
page.on('request', r => { const u=r.url(); if (u.includes('/api/metrics')||u.includes('/api/agent-context')) calls.push(u.replace('https://lyftai.io','')) })
page.on('console', m => { if (m.type()==='error') bad.push('JS: '+m.text().slice(0,110)) })
await page.goto('https://lyftai.io/', { waitUntil:'domcontentloaded', timeout:90000 })
await page.waitForTimeout(25000)
console.log('URL finale:', page.url())
const txt = await page.locator('body').innerText()
console.log('testo pagina (primi 300):', JSON.stringify(txt.slice(0,300)))
console.log('workspace mostrato:', (txt.match(/Anna Virgili|STMN/g)||[])[0] || '?')
console.log('importi a schermo:', (txt.match(/€\s?[\d.,]+/g)||[]).slice(0,8).join('  ') || 'NESSUNO')
console.log('chiamate metrics:', [...new Set(calls)].join(' | ') || 'nessuna')
console.log('errori:', bad.length ? [...new Set(bad)].slice(0,6).join('\n   ') : 'nessuno')
const full = await page.locator('body').innerText()
console.log('\n--- TESTO DASHBOARD (600-2200) ---')
console.log(full.slice(600, 2200))
await page.screenshot({ path:'/tmp/av_dash.png' })
await b.close()
