export const dynamic = 'force-dynamic'
export const maxDuration = 60
export const runtime = 'nodejs'

import { NextResponse } from 'next/server'
import { reportLogoBar } from '../../../../lib/reports/logo'

// Etichette PDF localizzate (poche → inline, self-contained).
const L = {
  it: { title: 'Report Incrementalità', sub: 'Contributo incrementale per canale', range: 'Periodo', rel: 'Affidabilità', totRev: 'Ricavo totale', baseline: 'Baseline organico', totInc: 'Incrementale totale', ch: 'Canale', spend: 'Spesa', repRoas: 'ROAS riportato', incRev: 'Ricavo incrementale', iRoas: 'ROAS incr.', mRoas: 'ROAS prossimo €', sat: 'Saturazione', carry: 'Carryover 90%', days: 'gg', note: 'Stima direzionale dai tuoi dati (MMM-lite). Per certezza causale, valida con un test geo-lift.', gen: 'Generato da LyftAI · Incrementalità', noData: 'Dati insufficienti per il calcolo.' },
  en: { title: 'Incrementality Report', sub: 'Incremental contribution by channel', range: 'Period', rel: 'Reliability', totRev: 'Total revenue', baseline: 'Organic baseline', totInc: 'Total incremental', ch: 'Channel', spend: 'Spend', repRoas: 'Reported ROAS', incRev: 'Incremental revenue', iRoas: 'Incr. ROAS', mRoas: 'Next-€ ROAS', sat: 'Saturation', carry: 'Carryover 90%', days: 'd', note: 'Directional estimate from your own data (MMM-lite). For causal certainty, validate with a geo-lift test.', gen: 'Generated by LyftAI · Incrementality', noData: 'Not enough data to compute.' },
  es: { title: 'Informe de Incrementalidad', sub: 'Contribución incremental por canal', range: 'Período', rel: 'Fiabilidad', totRev: 'Ingresos totales', baseline: 'Baseline orgánico', totInc: 'Incremental total', ch: 'Canal', spend: 'Gasto', repRoas: 'ROAS reportado', incRev: 'Ingreso incremental', iRoas: 'ROAS incr.', mRoas: 'ROAS próximo €', sat: 'Saturación', carry: 'Carryover 90%', days: 'd', note: 'Estimación direccional de tus propios datos (MMM-lite). Para certeza causal, valida con un test geo-lift.', gen: 'Generado por LyftAI · Incrementalidad', noData: 'Datos insuficientes para el cálculo.' },
  fr: { title: "Rapport d'Incrémentalité", sub: 'Contribution incrémentale par canal', range: 'Période', rel: 'Fiabilité', totRev: 'Revenu total', baseline: 'Baseline organique', totInc: 'Incrémental total', ch: 'Canal', spend: 'Dépense', repRoas: 'ROAS déclaré', incRev: 'Revenu incrémental', iRoas: 'ROAS incr.', mRoas: 'ROAS prochain €', sat: 'Saturation', carry: 'Carryover 90%', days: 'j', note: "Estimation directionnelle à partir de vos données (MMM-lite). Pour une certitude causale, validez avec un test geo-lift.", gen: 'Généré par LyftAI · Incrémentalité', noData: 'Données insuffisantes pour le calcul.' },
  de: { title: 'Inkrementalitäts-Report', sub: 'Inkrementeller Beitrag je Kanal', range: 'Zeitraum', rel: 'Zuverlässigkeit', totRev: 'Gesamtumsatz', baseline: 'Organische Baseline', totInc: 'Inkrementell gesamt', ch: 'Kanal', spend: 'Ausgaben', repRoas: 'Gemeldeter ROAS', incRev: 'Inkrementeller Umsatz', iRoas: 'Inkr. ROAS', mRoas: 'Nächster-€ ROAS', sat: 'Sättigung', carry: 'Carryover 90%', days: 'T', note: 'Richtungsweisende Schätzung aus deinen Daten (MMM-lite). Für kausale Sicherheit mit einem Geo-Lift-Test validieren.', gen: 'Erstellt von LyftAI · Inkrementalität', noData: 'Nicht genug Daten für die Berechnung.' },
}

async function internal(req, path) {
  try {
    const url = new URL(path, req.url)
    const r = await fetch(url, { headers: { cookie: req.headers.get('cookie') || '' }, cache: 'no-store', signal: AbortSignal.timeout(50000) })
    if (!r.ok) return null
    return await r.json().catch(() => null)
  } catch { return null }
}

function buildHtml(data, t, loc) {
  const nf = (n) => `€${Math.round(Number(n) || 0).toLocaleString(loc)}`
  const x = (n) => `${(Number(n) || 0).toFixed(2)}×`
  const pc = (n) => `${Math.round((Number(n) || 0) * 100)}%`
  const names = data.channelNames || {}
  const rows = (data.channels || []).map(c => `
    <tr>
      <td style="font-weight:700">${names[c.key] || c.key}</td>
      <td>${nf(c.spend)}</td>
      <td>${x(c.roasReported)}</td>
      <td style="font-weight:800;color:#0f766e">${nf(c.incrementalRevenue)}</td>
      <td>${x(c.iRoas)}</td>
      <td>${x(c.mRoas)}</td>
      <td>${pc(c.saturation)}</td>
      <td>${c.carryoverDays90} ${t.days}</td>
    </tr>`).join('')
  const inner = `
    <div class="hd">
      <div><div class="h1">${t.title}</div><div class="sub">${t.sub}</div></div>
      <div class="meta">${t.range}: ${data.range?.since} → ${data.range?.until}<br>${t.rel}: R² ${(data.r2 || 0).toFixed(2)}</div>
    </div>
    <div class="cards">
      <div class="card"><div class="cl">${t.totRev}</div><div class="cv">${nf(data.totalRevenue)}</div></div>
      <div class="card"><div class="cl">${t.baseline}</div><div class="cv">${nf(data.baselineRevenue)}</div></div>
      <div class="card"><div class="cl">${t.totInc}</div><div class="cv" style="color:#0f766e">${nf((data.channels || []).reduce((s, c) => s + c.incrementalRevenue, 0))}</div></div>
    </div>
    <table>
      <thead><tr><th>${t.ch}</th><th>${t.spend}</th><th>${t.repRoas}</th><th>${t.incRev}</th><th>${t.iRoas}</th><th>${t.mRoas}</th><th>${t.sat}</th><th>${t.carry}</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <div class="note">${t.note}</div>`
  return `<!doctype html><html><head><meta charset="utf-8"><style>
    *{font-family:-apple-system,'Segoe UI',Arial,sans-serif;box-sizing:border-box}
    body{margin:0;padding:28px 30px;color:#222;font-size:13px}
    .hd{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #eee;padding-bottom:16px;margin-bottom:20px}
    .h1{font-size:24px;font-weight:800;color:#111} .sub{color:#666;margin-top:4px}
    .meta{text-align:right;color:#888;font-size:11px;line-height:1.6}
    .cards{display:flex;gap:12px;margin-bottom:18px}
    .card{flex:1;border:1px solid #eee;border-radius:12px;padding:14px 16px}
    .cl{font-size:10px;text-transform:uppercase;letter-spacing:.05em;color:#999;font-weight:700} .cv{font-size:22px;font-weight:800;margin-top:4px}
    table{width:100%;border-collapse:collapse;margin-top:6px} th{text-align:left;font-size:10px;text-transform:uppercase;color:#999;border-bottom:2px solid #eee;padding:8px 8px}
    td{padding:9px 8px;border-bottom:1px solid #f2f2f2;font-size:12.5px}
    .note{margin-top:18px;font-size:11px;color:#888;background:#fafafa;border-radius:10px;padding:12px 14px}
  </style></head><body>${reportLogoBar ? reportLogoBar() : ''}${inner}<div style="margin-top:26px;color:#bbb;font-size:10px;text-align:center">${t.gen}</div></body></html>`
}

async function renderPdf(html) {
  const token = process.env.BROWSERLESS_TOKEN
  if (!token) return { error: 'BROWSERLESS_TOKEN mancante' }
  let browser
  try {
    const { default: puppeteer } = await import('puppeteer-core')
    const endpoint = process.env.BROWSERLESS_ENDPOINT || 'production-lon.browserless.io'
    browser = await puppeteer.connect({ browserWSEndpoint: `wss://${endpoint}/?token=${encodeURIComponent(token)}` })
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'load', timeout: 30000 })
    await page.emulateMediaType('screen')
    const buf = await page.pdf({ format: 'A4', landscape: true, printBackground: true, margin: { top: '16px', bottom: '16px', left: '14px', right: '14px' } })
    return { buf }
  } catch (e) { return { error: e?.message || 'render error' } } finally { if (browser) await browser.disconnect().catch(() => {}) }
}

export async function GET(req) {
  const { searchParams } = new URL(req.url)
  const days = searchParams.get('days') || '150'
  const loc = (searchParams.get('locale') || 'it').slice(0, 2)
  const t = L[loc] || L.it
  const nloc = { it: 'it-IT', en: 'en-US', es: 'es-ES', fr: 'fr-FR', de: 'de-DE' }[loc] || 'it-IT'

  const data = await internal(req, `/api/incrementality?days=${days}&locale=${loc}`)
  if (!data || !data.ok) {
    return new NextResponse(`<html><body style="font-family:sans-serif;padding:40px;color:#666">${t.noData}</body></html>`, { headers: { 'Content-Type': 'text/html; charset=utf-8' } })
  }

  const html = buildHtml(data, t, nloc)
  const { buf, error } = await renderPdf(html)
  if (!buf) return new NextResponse(html, { headers: { 'Content-Type': 'text/html; charset=utf-8', 'X-PDF-Error': (error || 'unknown').slice(0, 120) } })
  const fname = `LyftAI_Incrementality_${new Date().toISOString().slice(0, 10)}.pdf`
  return new NextResponse(buf, { headers: { 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="${fname}"` } })
}
