// I testi della landing, in cinque lingue. L'italiano e' l'originale: le altre lingue lo seguono
// chiave per chiave (stesso numero di voci in ogni elenco).
//
// REGOLE per chi li tocca:
// - Solo cose che il prodotto fa OGGI. Niente numeri di risultato ("+34% ROAS"), niente
//   testimonianze: finche' non ce ne sono di vere e verificabili, non si scrivono.
// - Tolte il 21 set 2026 e da non rimettere: Lighthouse, Performance Agent, Creative Intel,
//   white-label, generatore di creativita', chiamate vocali con gli agenti.
// - Le funzioni per chi rivende piu' marchi (Prezzi, marketplace, negozi fisici) si dicono
//   come tali: agli altri negozi non compaiono.

const it = {
  nav: {
    prodotto: 'Prodotto', agenzie: 'Agenzie', prezzi: 'Prezzi', domande: 'Domande',
    accedi: 'Accedi', prova: 'Prova gratis', menu: 'Menu', lingua: 'Lingua', tema: 'Tema', giorno: 'Tema giorno', notte: 'Tema notte',
  },
  apertura: {
    etichetta: 'Per i negozi Shopify',
    titolo: 'Quanto vendi, quanto spendi, quanto ti resta.',
    // Il titolo a macchina da scrivere: «Quanto» resta, il resto si scrive e si cancella a turno.
    titoloPrima: 'Quanto ', oggetti: ['vendi, ora per ora.', 'spendi su Meta e Google.', 'ti resta su ogni prodotto.', 'ti resta da ogni cliente.'],
    sotto: 'LyftAI mette insieme Shopify, Meta, Google e le tue email in un conto solo, aggiornato mentre vendi. E ti dice cosa fare dopo.',
    prova: 'Prova gratis per 14 giorni',
    demo: 'Guarda la demo',
    promesse: ['Nessuna carta richiesta', 'Si collega in pochi minuti', 'In cinque lingue'],
    alt: 'La Dashboard di LyftAI: fatturato, spesa pubblicitaria e MER confrontati con il periodo prima, e i visitatori in tempo reale sul globo',
    globo: { sessioni: 'Sul sito adesso', ordini: 'Ordini oggi', nuovo: 'Nuovo ordine', nota: 'Negozio d’esempio, dati simulati' },
  },
  fonti: { etichetta: 'Legge i dati da' },
  blocchi: [
    {
      id: 'productPerformance',
      etichetta: 'Performance prodotti',
      titolo: 'Il margine vero di ogni prodotto.',
      testo: 'Dal venduto togliamo l’IVA, il costo del prodotto e la pubblicità che gli spetta. Quello che resta è il margine, riga per riga.',
      punti: [
        ['IVA letta da Shopify,', 'prodotto per prodotto: 22%, 10% o 4%, come l’hai impostata nel negozio.'],
        ['Pubblicità attribuita dal link dell’annuncio:', 'la campagna che porta a un prodotto pesa su quel prodotto, il resto si ripartisce sul fatturato.'],
        ['Costo per variante, con lo storico:', 'se il fornitore cambia prezzo, i mesi passati restano giusti.'],
      ],
      alt: 'Tabella Performance prodotti: venduto, IVA, netto, costo, pubblicità e margine per ogni prodotto',
    },
    {
      id: 'kpiBrain',
      etichetta: 'KPI Brain',
      titolo: 'La pubblicità, misurata sugli ordini veri.',
      testo: 'MER, costo per ordine e costo per cliente nuovo, calcolati sulla spesa di Meta e Google e sugli ordini di Shopify. Non su quello che le piattaforme dicono di aver venduto.',
      punti: [
        ['Oggi contro ieri, alla stessa ora:', 'alle 11 del mattino confronti le 11 di ieri, non la giornata intera.'],
        ['Come nasce ogni numero:', 'passaci sopra e vedi da dove arriva e come è calcolato.'],
        ['Meta e Google fianco a fianco:', 'spesa, ROAS, stanchezza delle creatività e dove spostare il budget.'],
      ],
      alt: 'KPI Brain: fatturato, MER, costo per cliente, spesa totale e LTV con le fonti di ogni numero',
    },
    {
      id: 'incrContribution',
      etichetta: 'Incrementalità',
      titolo: 'Quanto vende davvero ogni canale.',
      testo: 'Una parte delle vendite che Meta e Google si attribuiscono sarebbe arrivata comunque. LyftAI stima quanto aggiunge davvero ogni canale e dove il prossimo euro rende di più.',
      punti: [
        ['Contributo e curve di risposta:', 'vedi quando un canale comincia a saturare.'],
        ['Simulatore di budget:', 'sposti la spesa e guardi l’effetto previsto sul fatturato.'],
        ['Geo-lift sulle regioni:', 'per provarlo sul campo, con regioni di test e di controllo scelte sulle tue vendite Shopify.'],
      ],
      alt: 'Contributo incrementale di Meta e Google rispetto alle vendite che arrivano comunque',
    },
    {
      id: 'clienti',
      etichetta: 'Clienti',
      titolo: 'Chi torna, e chi sta per andarsene.',
      testo: 'I clienti divisi per come comprano: nuovi, fedeli, a rischio, dormienti. Per ogni gruppo sai quanto vale e prepari la campagna giusta in un clic.',
      punti: [
        ['LTV lordo e netto:', 'quanto vale un cliente dopo i costi, non solo quanto fattura.'],
        ['Coorti per mese:', 'quanti clienti di ogni mese tornano a comprare, e dopo quanto.'],
        ['Email marketing:', 'Klaviyo, Mailchimp o Omnisend, con campagne, flussi e fatturato nello stesso posto.'],
      ],
      alt: 'Clienti divisi in segmenti con valore, ordini medi, giorni tra gli ordini e vendite totali',
    },
    {
      id: 'pnl',
      etichetta: 'Conti e report',
      titolo: 'I conti del mese, fino all’EBIT.',
      testo: 'Ricavi netti, costo del venduto, pubblicità e le spese che inserisci tu: il conto economico si compone da solo, mese per mese, con la variazione sul mese prima.',
      punti: [
        ['Corrispettivi per il commercialista:', 'vendite per giorno e per paese, con l’IVA registrata da Shopify, in un file Excel.'],
        ['Report in PDF:', 'settimana, mese, trimestre e anno, nella lingua di chi li legge.'],
        ['Il film della settimana:', 'i numeri della settimana uno dopo l’altro, da guardare invece che da leggere.'],
      ],
      alt: 'Conto economico mensile con ricavi, costi ed EBIT',
    },
  ],
  ai: {
    etichetta: 'Il Cervello',
    titolo: 'Un’AI che conosce il tuo negozio.',
    sotto: 'Le racconti il tuo marchio una volta: prodotti, clienti, tono di voce. Da lì risponde con i tuoi numeri, non con consigli buoni per tutti.',
    voci: [
      { titolo: 'Chiedi, e risponde con i dati', testo: '«Perché è calato il margine questa settimana?» Legge Shopify, Meta e Google e ti dice cosa è cambiato.' },
      { titolo: 'Il briefing del mattino', testo: 'Cosa è successo ieri e cosa guardare oggi, prima ancora di aprire le tabelle.' },
      { titolo: 'Una squadra per ogni area', testo: 'Agenti dedicati a pubblicità, SEO, sito e numeri, che lavorano tutti sugli stessi dati.' },
    ],
    chat: {
      negozio: 'negozio demo', scrive: 'sta scrivendo…',
      scambi: [
        { d: 'Perché è calato il margine questa settimana?', r: 'È sceso di 2,4 punti, per due motivi: su Meta la campagna «Prospecting – Video» porta clienti nuovi a €41 l’uno, contro €29 del mese scorso; e le Scarpe Running AirFlow sono andate soprattutto in sconto. Sposterei €40 al giorno sul retargeting del catalogo, che oggi rende 4,1×.' },
        { d: 'Quali prodotti conviene spingere su Google?', r: 'Borsone Duffel 40L, Felpa Hoodie Essential e Guanti Training Grip: insieme fanno il 22% del margine ma prendono solo il 6% della spesa Google. Sono i primi tre da mettere in una campagna dedicata.' },
        { d: 'Come sta andando oggi?', r: 'Alle 11 sei a €2.140, il 12% sopra ieri alla stessa ora. MER 3,6×. Gli ordini arrivano soprattutto da Milano e Roma; nessuna anomalia su Meta e Google.' },
      ],
    },
  },
  tutto: {
    etichetta: 'Tutto incluso',
    titolo: 'Ogni strumento, in ogni piano.',
    sotto: 'Il prezzo cresce con i tuoi ordini, mai con le funzioni.',
    aree: [
      { icona: 'grid', titolo: 'Vendite', voci: ['Dashboard e sala di controllo', 'Inventario e taglie esaurite', 'Performance e costi prodotto', 'LTV e coorti'] },
      { icona: 'target', titolo: 'Meta', voci: ['KPI e dettaglio per annuncio', 'Creatività e loro stanchezza', 'Consigli sul budget', 'Campagne lead'] },
      { icona: 'search', titolo: 'Google', voci: ['KPI e dettaglio campagne', 'Prodotti e verdetti', 'Consigli sul budget'] },
      { icona: 'layers', titolo: 'Incrementalità', voci: ['Contributo incrementale', 'Curve di risposta', 'Simulatore di budget', 'Geo-lift'] },
      { icona: 'users', titolo: 'Clienti ed email', voci: ['Segmenti per comportamento', 'Idee di campagna con l’AI', 'Klaviyo, Mailchimp, Omnisend'] },
      { icona: 'scan', titolo: 'Sito e SEO', voci: ['Audit SEO e Search Console', 'Parole chiave e visibilità nelle AI', 'Conversioni e scansione del sito'] },
      { icona: 'euro', titolo: 'Conti e report', voci: ['Conto economico', 'Corrispettivi', 'Report di settimana, mese, trimestre, anno', 'Simulatore del conto'] },
      { icona: 'kanban', titolo: 'Lavoro di squadra', voci: ['Progetti e task', 'Calendario, ferie e permessi', 'Lyftimer, le ore di lavoro', 'LyftTalk, la chat del team'] },
    ],
    rivenditori: {
      titolo: 'Se vendi più marchi',
      testo: 'Prezzi della concorrenza, marchi più venduti, vendite di marketplace e negozi fisici tenute fuori dal conto della pubblicità. Si accendono solo per chi ne ha bisogno.',
    },
  },
  agenzie: {
    etichetta: 'Per agenzie e freelance',
    titolo: 'Tutti i clienti, un solo accesso.',
    sotto: 'Un’area separata per ogni cliente, con i suoi dati e le sue integrazioni. Passi dall’uno all’altro in un clic.',
    voci: [
      { titolo: 'Dati separati', testo: 'Ogni cliente vede solo il suo. Tu li vedi tutti.' },
      { titolo: 'Cinque lingue', testo: 'Italiano, inglese, spagnolo, francese e tedesco, anche nei report in PDF.' },
      { titolo: 'Prezzo per numero di clienti', testo: 'Tutti gli strumenti inclusi: paghi in base a quante aziende gestisci.' },
    ],
    cta: 'Vedi i piani per agenzie',
  },
  prezzi: {
    etichetta: 'Prezzi',
    titolo: 'Paghi per la tua dimensione. Gli strumenti ci sono tutti.',
    sotto: '14 giorni gratis, senza carta. Annulli quando vuoi.',
    garanzia: 'Il piano giusto lo decidono gli ordini Shopify reali: sali di piano solo quando cresci davvero.',
    founder: 'Founder: −30% a vita per le prime 100 aziende, anche sul piano annuale.',
    pubblico: { brand: 'Aziende', agenzie: 'Agenzie e freelance' },
    agenzieSotto: 'Gestisci tutti i clienti da un posto solo. Paghi per numero di aziende e passi dall’una all’altra in un clic.',
    cadenza: { mensile: 'Mensile', annuale: 'Annuale' },
    dueMesi: '2 mesi gratis',
    alMese: '/mese',
    fatturato: 'fatturati una volta l’anno',
    risparmi: 'risparmi',
    piani: [
      { id: 'starter', nome: 'Starter', prezzo: 69, riga: 'Fino a 500 ordini al mese.', voci: ['Tutti gli strumenti inclusi', 'Tutte le integrazioni', '2 persone del team', 'Assistenza via email entro 48 ore'], cta: 'Inizia con Starter' },
      { id: 'growth', nome: 'Growth', prezzo: 149, riga: 'Da 500 a 2.000 ordini al mese.', voci: ['Tutti gli strumenti inclusi', 'Tutte le integrazioni', '5 persone del team', 'Assistenza prioritaria entro 12 ore'], cta: 'Inizia con Growth', forte: 'Il più scelto' },
      { id: 'scale', nome: 'Scale', prezzo: 299, riga: 'Da 2.000 a 7.000 ordini al mese.', voci: ['Tutti gli strumenti inclusi', 'Tutte le integrazioni', 'Persone del team illimitate', 'Una persona dedicata a te'], cta: 'Inizia con Scale' },
      { id: 'enterprise', nome: 'Enterprise', prezzo: 599, riga: 'Oltre 7.000 ordini al mese.', voci: ['Tutti gli strumenti inclusi', 'Integrazioni su misura', 'Avvio seguito da noi, con SLA', 'Un account manager dedicato'], cta: 'Inizia con Enterprise' },
    ],
  },
  domande: {
    etichetta: 'Domande',
    titolo: 'Le domande di chi comincia.',
    voci: [
      { q: 'Come fa LyftAI a conoscere il mio marchio?', a: 'Nella sezione Brand Identity scrivi chi sei, a chi vendi, come parli e cosa non va mai detto. L’AI rilegge queste informazioni a ogni risposta.' },
      { q: 'Da dove arrivano i numeri?', a: 'Dalle piattaforme che colleghi: Shopify per ordini, IVA e clienti; Meta e Google per la spesa; GA4 e Search Console per il traffico. Ogni numero dice da quale fonte viene.' },
      { q: 'Vendo anche su marketplace o in negozio. Funziona lo stesso?', a: 'Sì. Le vendite di marketplace e negozi fisici si tengono fuori dal conto della pubblicità, così MER e costo per cliente restano puliti. Nel conto economico invece ci sono.' },
      { q: 'I miei dati sono al sicuro?', a: 'Ogni azienda ha le sue credenziali e i suoi dati, separati da quelli degli altri. Le connessioni sono cifrate e i dati non vengono mai condivisi tra clienti.' },
      { q: 'Quanto ci vuole per partire?', a: 'Pochi minuti. Colleghi Shopify, Meta, Google e il tuo strumento email con un clic, senza copiare chiavi. I primi numeri arrivano mentre finisci.' },
      { q: 'Come funziona la prova gratuita?', a: '14 giorni con tutto incluso, senza carta. Alla fine scegli un piano, oppure lasci perdere.' },
      { q: 'Posso annullare quando voglio?', a: 'Sì. Annulli dal portale dei pagamenti, in qualsiasi momento e senza penali.' },
      { q: 'Siete conformi al GDPR?', a: 'Sì. Il DPA è disponibile, puoi esportare o cancellare l’account da solo e i fornitori che trattano i dati sono elencati nell’informativa privacy.' },
    ],
  },
  contatti: {
    etichetta: 'Parliamone',
    titolo: 'Vuoi vederlo sui tuoi dati?',
    sotto: 'Scrivici e ti rispondiamo entro 24 ore. Niente venditori: rispondiamo noi.',
    nome: 'Nome e cognome', nomeEsempio: 'Mario Rossi',
    azienda: 'Azienda', aziendaEsempio: 'Acme Srl',
    email: 'Email', emailEsempio: 'mario@acme.it',
    telefono: 'Telefono', telefonoEsempio: '+39 333 1234567',
    sito: 'Sito web', sitoEsempio: 'https://acme.it',
    fatturatoAnnuo: 'Fatturato annuo', scegli: 'Scegli',
    messaggio: 'Messaggio', messaggioEsempio: 'Su quali piattaforme vendi e cosa vorresti capire meglio?',
    richiesti: 'Servono almeno nome, azienda ed email.',
    invia: 'Invia',
    invio: 'Invio…',
    fattoTitolo: 'Messaggio arrivato.',
    fattoTesto: 'Ti rispondiamo entro 24 ore via email.',
    avvertenza: 'I dati vanno a LYFT SRL e servono solo per risponderti. Nessuna newsletter.',
  },
  chiusura: {
    titolo: 'Smetti di indovinare.',
    sotto: 'Collega il negozio e in pochi minuti hai i tuoi numeri, messi in fila.',
    prova: 'Prova gratis per 14 giorni',
    demo: 'Guarda la demo',
  },
  piede: {
    tagline: 'I numeri del tuo e-commerce, in un posto solo.',
    prodotto: 'Prodotto', azienda: 'Azienda', legale: 'Note legali',
    privacy: 'Privacy', termini: 'Termini di servizio', dpa: 'Trattamento dei dati (DPA)',
    diritti: 'Tutti i diritti riservati.',
  },
}

// Le altre lingue: tradotte dall'italiano il 21 set 2026, con i nomi delle aree presi dai
// dizionari dell'app (stesse parole che il cliente trova dentro il prodotto).

const en = {
  nav: {
    prodotto: 'Product', agenzie: 'Agencies', prezzi: 'Pricing', domande: 'FAQ',
    accedi: 'Log in', prova: 'Try it free', menu: 'Menu', lingua: 'Language', tema: 'Theme', giorno: 'Light mode', notte: 'Dark mode',
  },
  apertura: {
    etichetta: 'For Shopify stores',
    titolo: 'What you sell, what you spend, what you keep.',
    // Il titolo a macchina da scrivere: «What you» resta, il resto si scrive e si cancella a turno.
    titoloPrima: 'What you ', oggetti: ['sell, hour by hour.', 'spend on Meta and Google.', 'keep on every product.', 'keep from every customer.'],
    sotto: 'LyftAI brings Shopify, Meta, Google and your email into one set of numbers, updated as you sell. And it tells you what to do next.',
    prova: 'Try it free for 14 days',
    demo: 'Watch the demo',
    promesse: ['No card required', 'Connects in minutes', 'In five languages'],
    alt: 'The LyftAI Dashboard: revenue, ad spend and MER compared with the previous period, and live visitors on the globe',
    globo: { sessioni: 'On the site now', ordini: 'Orders today', nuovo: 'New order', nota: 'Sample store, simulated data' },
  },
  fonti: { etichetta: 'Reads data from' },
  blocchi: [
    {
      id: 'productPerformance',
      etichetta: 'Product Performance',
      titolo: 'The real margin of every product.',
      testo: 'From what you sell we take out VAT, the product cost and its share of the ad spend. What’s left is the margin, line by line.',
      punti: [
        ['VAT read from Shopify,', 'product by product, at the rate you set in your store.'],
        ['Ad spend assigned by the ad’s link:', 'the campaign that leads to a product counts against that product; the rest is shared out by revenue.'],
        ['Cost per variant, with history:', 'if a supplier changes its price, past months stay correct.'],
      ],
      alt: 'Product Performance table: sales, VAT, net, cost, advertising and margin for each product',
    },
    {
      id: 'kpiBrain',
      etichetta: 'KPI Brain',
      titolo: 'Advertising, measured on real orders.',
      testo: 'MER, cost per order and cost per new customer, calculated from Meta and Google spend and Shopify orders. Not from what the platforms say they sold.',
      punti: [
        ['Today against yesterday, at the same time:', 'at 11 a.m. you compare with 11 a.m. yesterday, not with the whole day.'],
        ['Where every number comes from:', 'hover over it to see its source and how it’s calculated.'],
        ['Meta and Google side by side:', 'spend, ROAS, creative fatigue and where to move budget.'],
      ],
      alt: 'KPI Brain: revenue, MER, cost per customer, total spend and LTV, with the source of every number',
    },
    {
      id: 'incrContribution',
      etichetta: 'Incrementality',
      titolo: 'What each channel really sells.',
      testo: 'Some of the sales Meta and Google take credit for would have come in anyway. LyftAI estimates what each channel really adds, and where your next euro earns the most.',
      punti: [
        ['Contribution and response curves:', 'see when a channel starts to saturate.'],
        ['Budget simulator:', 'move spend around and see the expected effect on revenue.'],
        ['Geo-lift by region:', 'to test it in the field, with test and control regions chosen from your Shopify sales.'],
      ],
      alt: 'Incremental contribution of Meta and Google compared with the sales that come in anyway',
    },
    {
      id: 'clienti',
      etichetta: 'Customers',
      titolo: 'Who comes back, and who’s about to leave.',
      testo: 'Your customers grouped by how they buy: new, loyal, at risk, dormant. For each group you know what it’s worth, and you set up the right campaign in one click.',
      punti: [
        ['Gross and net LTV:', 'what a customer is worth after costs, not just the revenue they bring.'],
        ['Monthly cohorts:', 'how many customers from each month come back to buy, and after how long.'],
        ['Email marketing:', 'Klaviyo, Mailchimp or Omnisend, with campaigns, flows and revenue in one place.'],
      ],
      alt: 'Customers split into segments with value, average orders, days between orders and total sales',
    },
    {
      id: 'pnl',
      etichetta: 'Finance and reports',
      titolo: 'The month’s P&L, down to EBIT.',
      testo: 'Net revenue, cost of goods sold, advertising and the expenses you enter: the P&L puts itself together, month by month, with the change from the month before.',
      punti: [
        ['Daily sales register for your accountant:', 'sales by day and by country, with the VAT recorded by Shopify, in an Excel file.'],
        ['PDF reports:', 'week, month, quarter and year, in the language of whoever reads them.'],
        ['The week, on film:', 'the week’s numbers one after another, to watch instead of read.'],
      ],
      alt: 'Monthly P&L with revenue, costs and EBIT',
    },
  ],
  ai: {
    etichetta: 'The Brain',
    titolo: 'An AI that knows your store.',
    sotto: 'Tell it about your brand once: products, customers, tone of voice. From then on it answers with your numbers, not with advice that fits everyone.',
    voci: [
      { titolo: 'Ask, and it answers with data', testo: '“Why did the margin drop this week?” It reads Shopify, Meta and Google and tells you what changed.' },
      { titolo: 'The morning briefing', testo: 'What happened yesterday and what to look at today, before you even open the tables.' },
      { titolo: 'A team for every area', testo: 'Agents for advertising, SEO, the website and the numbers, all working on the same data.' },
    ],
    chat: {
      negozio: 'demo store', scrive: 'typing…',
      scambi: [
        { d: 'Why did the margin drop this week?', r: 'It fell 2.4 points, for two reasons: on Meta, the “Prospecting – Video” campaign is bringing in new customers at €41 each, against €29 last month; and the Scarpe Running AirFlow sold mostly on discount. I’d move €40 a day to catalogue retargeting, which is returning 4.1× right now.' },
        { d: 'Which products should we push on Google?', r: 'Borsone Duffel 40L, Felpa Hoodie Essential and Guanti Training Grip: together they make 22% of the margin but take only 6% of Google spend. They’re the first three to put in a dedicated campaign.' },
        { d: 'How are we doing today?', r: 'At 11 a.m. you’re at €2,140, 12% above yesterday at the same time. MER 3.6×. Orders are coming mostly from Milan and Rome; nothing unusual on Meta or Google.' },
      ],
    },
  },
  tutto: {
    etichetta: 'All included',
    titolo: 'Every tool, in every plan.',
    sotto: 'The price grows with your orders, never with features.',
    aree: [
      { icona: 'grid', titolo: 'Sales', voci: ['Dashboard and control room', 'Inventory and sold-out sizes', 'Product performance and costs', 'LTV and cohorts'] },
      { icona: 'target', titolo: 'Meta', voci: ['KPIs and ad-level detail', 'Creatives and their fatigue', 'Budget advice', 'Lead campaigns'] },
      { icona: 'search', titolo: 'Google', voci: ['KPIs and campaign detail', 'Products and verdicts', 'Budget advice'] },
      { icona: 'layers', titolo: 'Incrementality', voci: ['Incremental contribution', 'Response curves', 'Budget simulator', 'Geo-lift'] },
      { icona: 'users', titolo: 'Customers and email', voci: ['Segments by behavior', 'Campaign ideas with AI', 'Klaviyo, Mailchimp, Omnisend'] },
      { icona: 'scan', titolo: 'Website and SEO', voci: ['SEO audit and Search Console', 'Keywords and visibility in AI answers', 'Conversions and site scan'] },
      { icona: 'euro', titolo: 'Finance and reports', voci: ['P&L statement', 'Daily sales register', 'Weekly, monthly, quarterly and yearly reports', 'P&L simulator'] },
      { icona: 'kanban', titolo: 'Teamwork', voci: ['Projects and tasks', 'Calendar and time off', 'Lyftimer, for hours worked', 'LyftTalk, the team chat'] },
    ],
    rivenditori: {
      titolo: 'If you sell several brands',
      testo: 'Competitor prices, best-selling brands, and marketplace and in-store sales kept out of the advertising numbers. They switch on only for those who need them.',
    },
  },
  agenzie: {
    etichetta: 'For agencies and freelancers',
    titolo: 'All your clients, one login.',
    sotto: 'A separate space for each client, with its own data and integrations. Switch from one to the next in one click.',
    voci: [
      { titolo: 'Separate data', testo: 'Each client sees only their own. You see them all.' },
      { titolo: 'Five languages', testo: 'Italian, English, Spanish, French and German, in the PDF reports too.' },
      { titolo: 'Priced by number of clients', testo: 'Every tool included: you pay for how many businesses you manage.' },
    ],
    cta: 'See agency plans',
  },
  prezzi: {
    etichetta: 'Pricing',
    titolo: 'Pay for your size. You get every tool.',
    sotto: '14 days free, no card. Cancel anytime.',
    garanzia: 'Your real Shopify orders decide the right plan: you move up only when you actually grow.',
    founder: 'Founder: −30% for life for the first 100 businesses, on the yearly plan too.',
    pubblico: { brand: 'Brands', agenzie: 'Agencies and freelancers' },
    agenzieSotto: 'Manage every client from one place. You pay by number of businesses and switch between them in one click.',
    cadenza: { mensile: 'Monthly', annuale: 'Yearly' },
    dueMesi: '2 months free',
    alMese: '/month',
    fatturato: 'billed once a year',
    risparmi: 'you save',
    piani: [
      { id: 'starter', nome: 'Starter', prezzo: 69, riga: 'Up to 500 orders a month.', voci: ['Every tool included', 'Every integration', '2 team members', 'Email support within 48 hours'], cta: 'Start with Starter' },
      { id: 'growth', nome: 'Growth', prezzo: 149, riga: 'From 500 to 2,000 orders a month.', voci: ['Every tool included', 'Every integration', '5 team members', 'Priority support within 12 hours'], cta: 'Start with Growth', forte: 'Most popular' },
      { id: 'scale', nome: 'Scale', prezzo: 299, riga: 'From 2,000 to 7,000 orders a month.', voci: ['Every tool included', 'Every integration', 'Unlimited team members', 'A dedicated contact person'], cta: 'Start with Scale' },
      { id: 'enterprise', nome: 'Enterprise', prezzo: 599, riga: 'Over 7,000 orders a month.', voci: ['Every tool included', 'Custom integrations', 'Onboarding led by us, with SLA', 'A dedicated account manager'], cta: 'Start with Enterprise' },
    ],
  },
  domande: {
    etichetta: 'Questions',
    titolo: 'What people ask when they start.',
    voci: [
      { q: 'How does LyftAI get to know my brand?', a: 'In the Brand Identity section you write who you are, who you sell to, how you speak and what must never be said. The AI rereads this with every answer.' },
      { q: 'Where do the numbers come from?', a: 'From the platforms you connect: Shopify for orders, VAT and customers; Meta and Google for spend; GA4 and Search Console for traffic. Every number shows which source it comes from.' },
      { q: 'I also sell on marketplaces or in a physical store. Does it still work?', a: 'Yes. Marketplace and in-store sales are kept out of the advertising numbers, so MER and cost per customer stay clean. In the P&L, they are included.' },
      { q: 'Is my data safe?', a: 'Each business has its own credentials and its own data, kept apart from everyone else’s. Connections are encrypted, and data is never shared between customers.' },
      { q: 'How long does it take to get started?', a: 'A few minutes. You connect Shopify, Meta, Google and your email tool with one click, without copying keys. The first numbers arrive while you finish.' },
      { q: 'How does the free trial work?', a: '14 days with everything included, no card. At the end you choose a plan, or you let it go.' },
      { q: 'Can I cancel anytime?', a: 'Yes. You cancel from the billing portal, at any time and with no penalties.' },
      { q: 'Are you GDPR compliant?', a: 'Yes. The DPA is available, you can export or delete your account yourself, and the providers that process data are listed in the privacy policy.' },
    ],
  },
  contatti: {
    etichetta: 'Let’s talk',
    titolo: 'Want to see it on your own data?',
    sotto: 'Write to us and we’ll reply within 24 hours. No salespeople: we answer ourselves.',
    nome: 'Full name', nomeEsempio: 'John Smith',
    azienda: 'Company', aziendaEsempio: 'Acme Ltd',
    email: 'Email', emailEsempio: 'john@acme.com',
    telefono: 'Phone', telefonoEsempio: '+44 7700 900123',
    sito: 'Website', sitoEsempio: 'https://acme.com',
    fatturatoAnnuo: 'Annual revenue', scegli: 'Choose',
    messaggio: 'Message', messaggioEsempio: 'Which platforms do you sell on, and what would you like to understand better?',
    richiesti: 'We need at least your name, company and email.',
    invia: 'Send',
    invio: 'Sending…',
    fattoTitolo: 'Message received.',
    fattoTesto: 'We’ll reply by email within 24 hours.',
    avvertenza: 'Your details go to LYFT SRL and are used only to reply to you. No newsletter.',
  },
  chiusura: {
    titolo: 'Stop guessing.',
    sotto: 'Connect your store and in a few minutes your numbers are there, all lined up.',
    prova: 'Try it free for 14 days',
    demo: 'Watch the demo',
  },
  piede: {
    tagline: 'Your e-commerce numbers, in one place.',
    prodotto: 'Product', azienda: 'Company', legale: 'Legal',
    privacy: 'Privacy', termini: 'Terms of service', dpa: 'Data processing (DPA)',
    diritti: 'All rights reserved.',
  },
}

const es = {
  nav: {
    prodotto: 'Producto', agenzie: 'Agencias', prezzi: 'Precios', domande: 'Preguntas',
    accedi: 'Entrar', prova: 'Prueba gratis', menu: 'Menú', lingua: 'Idioma', tema: 'Tema', giorno: 'Modo claro', notte: 'Modo oscuro',
  },
  apertura: {
    etichetta: 'Para tiendas Shopify',
    titolo: 'Cuánto vendes, cuánto gastas, cuánto te queda.',
    // Il titolo a macchina da scrivere: «Cuánto» resta, il resto si scrive e si cancella a turno.
    titoloPrima: 'Cuánto ', oggetti: ['vendes, hora a hora.', 'gastas en Meta y Google.', 'te queda de cada producto.', 'te queda de cada cliente.'],
    sotto: 'LyftAI junta Shopify, Meta, Google y tu email en un solo lugar, con las cuentas al día mientras vendes. Y te dice qué hacer después.',
    prova: 'Prueba 14 días gratis',
    demo: 'Ver la demo',
    promesse: ['Sin tarjeta', 'Se conecta en pocos minutos', 'En cinco idiomas'],
    alt: 'La Dashboard de LyftAI: facturación, gasto publicitario y MER comparados con el periodo anterior, y los visitantes en tiempo real sobre el globo',
    globo: { sessioni: 'En la web ahora', ordini: 'Pedidos hoy', nuovo: 'Nuevo pedido', nota: 'Tienda de ejemplo, datos simulados' },
  },
  fonti: { etichetta: 'Lee los datos de' },
  blocchi: [
    {
      id: 'productPerformance',
      etichetta: 'Rendimiento de productos',
      titolo: 'El margen real de cada producto.',
      testo: 'A lo vendido le quitamos el IVA, el coste del producto y la publicidad que le corresponde. Lo que queda es el margen, línea por línea.',
      punti: [
        ['IVA leído de Shopify,', 'producto por producto, con el tipo que tienes configurado en tu tienda.'],
        ['Publicidad asignada por el enlace del anuncio:', 'la campaña que lleva a un producto pesa sobre ese producto; el resto se reparte según la facturación.'],
        ['Coste por variante, con historial:', 'si el proveedor cambia el precio, los meses pasados siguen siendo correctos.'],
      ],
      alt: 'Tabla de Rendimiento de productos: vendido, IVA, neto, coste, publicidad y margen de cada producto',
    },
    {
      id: 'kpiBrain',
      etichetta: 'KPI Brain',
      titolo: 'La publicidad, medida sobre pedidos reales.',
      testo: 'MER, coste por pedido y coste por cliente nuevo, calculados con el gasto de Meta y Google y los pedidos de Shopify. No con lo que las plataformas dicen haber vendido.',
      punti: [
        ['Hoy contra ayer, a la misma hora:', 'a las 11:00 comparas con las 11:00 de ayer, no con el día entero.'],
        ['De dónde sale cada número:', 'pasa el cursor por encima y ves de dónde viene y cómo se calcula.'],
        ['Meta y Google, lado a lado:', 'gasto, ROAS, fatiga de las creatividades y adónde mover el presupuesto.'],
      ],
      alt: 'KPI Brain: facturación, MER, coste por cliente, gasto total y LTV, con la fuente de cada número',
    },
    {
      id: 'incrContribution',
      etichetta: 'Incrementalidad',
      titolo: 'Cuánto vende de verdad cada canal.',
      testo: 'Parte de las ventas que Meta y Google se atribuyen habría llegado igualmente. LyftAI estima cuánto aporta de verdad cada canal y dónde rinde más el próximo euro.',
      punti: [
        ['Contribución y curvas de respuesta:', 'ves cuándo un canal empieza a saturarse.'],
        ['Simulador de presupuesto:', 'mueves el gasto y ves el efecto previsto en la facturación.'],
        ['Geo-lift por regiones:', 'para comprobarlo sobre el terreno, con regiones de test y de control elegidas a partir de tus ventas en Shopify.'],
      ],
      alt: 'Contribución incremental de Meta y Google frente a las ventas que llegan igualmente',
    },
    {
      id: 'clienti',
      etichetta: 'Clientes',
      titolo: 'Quién vuelve, y quién está a punto de irse.',
      testo: 'Tus clientes agrupados según cómo compran: nuevos, fieles, en riesgo, dormidos. De cada grupo sabes cuánto vale y preparas la campaña adecuada en un clic.',
      punti: [
        ['LTV bruto y neto:', 'cuánto vale un cliente después de los costes, no solo cuánto factura.'],
        ['Cohortes por mes:', 'cuántos clientes de cada mes vuelven a comprar, y al cabo de cuánto tiempo.'],
        ['Email marketing:', 'Klaviyo, Mailchimp u Omnisend, con campañas, flujos y facturación en el mismo sitio.'],
      ],
      alt: 'Clientes divididos en segmentos con valor, pedidos medios, días entre pedidos y ventas totales',
    },
    {
      id: 'pnl',
      etichetta: 'Cuentas e informes',
      titolo: 'Las cuentas del mes, hasta el EBIT.',
      testo: 'Ingresos netos, coste de lo vendido, publicidad y los gastos que añades tú: la cuenta de resultados se monta sola, mes a mes, con la variación sobre el mes anterior.',
      punti: [
        ['Registro diario de ventas para tu asesor:', 'ventas por día y por país, con el IVA registrado por Shopify, en un archivo Excel.'],
        ['Informes en PDF:', 'semana, mes, trimestre y año, en el idioma de quien los lee.'],
        ['La película de la semana:', 'los números de la semana uno tras otro, para verlos en lugar de leerlos.'],
      ],
      alt: 'Cuenta de resultados mensual con ingresos, costes y EBIT',
    },
  ],
  ai: {
    etichetta: 'El Cerebro',
    titolo: 'Una IA que conoce tu tienda.',
    sotto: 'Le cuentas tu marca una vez: productos, clientes, tono de voz. A partir de ahí responde con tus números, no con consejos que valen para todos.',
    voci: [
      { titolo: 'Pregunta, y te responde con datos', testo: '«¿Por qué ha bajado el margen esta semana?» Lee Shopify, Meta y Google y te dice qué ha cambiado.' },
      { titolo: 'El resumen de la mañana', testo: 'Qué pasó ayer y qué mirar hoy, antes incluso de abrir las tablas.' },
      { titolo: 'Un equipo para cada área', testo: 'Agentes dedicados a publicidad, SEO, web y números, que trabajan todos sobre los mismos datos.' },
    ],
    chat: {
      negozio: 'tienda demo', scrive: 'escribiendo…',
      scambi: [
        { d: '¿Por qué ha bajado el margen esta semana?', r: 'Ha bajado 2,4 puntos, por dos motivos: en Meta, la campaña «Prospecting – Video» trae clientes nuevos a €41 cada uno, frente a €29 el mes pasado; y las Scarpe Running AirFlow se han vendido sobre todo con descuento. Pasaría €40 al día al retargeting del catálogo, que ahora rinde 4,1×.' },
        { d: '¿Qué productos conviene impulsar en Google?', r: 'Borsone Duffel 40L, Felpa Hoodie Essential y Guanti Training Grip: juntos suman el 22 % del margen, pero se llevan solo el 6 % del gasto en Google. Son los tres primeros para una campaña propia.' },
        { d: '¿Cómo vamos hoy?', r: 'A las 11 llevas €2.140, un 12 % más que ayer a la misma hora. MER 3,6×. Los pedidos llegan sobre todo de Milán y Roma; nada raro en Meta ni en Google.' },
      ],
    },
  },
  tutto: {
    etichetta: 'Todo incluido',
    titolo: 'Cada herramienta, en cada plan.',
    sotto: 'El precio crece con tus pedidos, nunca con las funciones.',
    aree: [
      { icona: 'grid', titolo: 'Ventas', voci: ['Dashboard y sala de control', 'Inventario y tallas agotadas', 'Rendimiento y costes de producto', 'LTV y cohortes'] },
      { icona: 'target', titolo: 'Meta', voci: ['KPI y detalle por anuncio', 'Creatividades y su fatiga', 'Consejos de presupuesto', 'Campañas de leads'] },
      { icona: 'search', titolo: 'Google', voci: ['KPI y detalle de campañas', 'Productos y veredictos', 'Consejos de presupuesto'] },
      { icona: 'layers', titolo: 'Incrementalidad', voci: ['Contribución incremental', 'Curvas de respuesta', 'Simulador de presupuesto', 'Geo-lift'] },
      { icona: 'users', titolo: 'Clientes y email', voci: ['Segmentos por comportamiento', 'Ideas de campaña con IA', 'Klaviyo, Mailchimp, Omnisend'] },
      { icona: 'scan', titolo: 'Web y SEO', voci: ['Auditoría SEO y Search Console', 'Palabras clave y visibilidad en las IA', 'Conversiones y análisis de la web'] },
      { icona: 'euro', titolo: 'Cuentas e informes', voci: ['Cuenta de resultados', 'Registro diario de ventas', 'Informes de semana, mes, trimestre, año', 'Simulador de la cuenta'] },
      { icona: 'kanban', titolo: 'Trabajo en equipo', voci: ['Proyectos y tareas', 'Calendario, vacaciones y permisos', 'Lyftimer, las horas de trabajo', 'LyftTalk, el chat del equipo'] },
    ],
    rivenditori: {
      titolo: 'Si vendes varias marcas',
      testo: 'Precios de la competencia, marcas más vendidas, y ventas de marketplaces y tiendas físicas fuera de las cuentas de la publicidad. Se activan solo para quien las necesita.',
    },
  },
  agenzie: {
    etichetta: 'Para agencias y freelance',
    titolo: 'Todos los clientes, un solo acceso.',
    sotto: 'Un espacio separado para cada cliente, con sus datos y sus integraciones. Pasas de uno a otro en un clic.',
    voci: [
      { titolo: 'Datos separados', testo: 'Cada cliente ve solo lo suyo. Tú los ves todos.' },
      { titolo: 'Cinco idiomas', testo: 'Italiano, inglés, español, francés y alemán, también en los informes PDF.' },
      { titolo: 'Precio por número de clientes', testo: 'Todas las herramientas incluidas: pagas según cuántas empresas gestionas.' },
    ],
    cta: 'Ver los planes para agencias',
  },
  prezzi: {
    etichetta: 'Precios',
    titolo: 'Pagas según tu tamaño. Tienes todas las herramientas.',
    sotto: '14 días gratis, sin tarjeta. Cancelas cuando quieras.',
    garanzia: 'El plan adecuado lo deciden tus pedidos reales de Shopify: subes de plan solo cuando creces de verdad.',
    founder: 'Founder: −30% de por vida para las primeras 100 empresas, también en el plan anual.',
    pubblico: { brand: 'Empresas', agenzie: 'Agencias y freelance' },
    agenzieSotto: 'Gestiona todos tus clientes desde un solo sitio. Pagas por número de empresas y pasas de una a otra en un clic.',
    cadenza: { mensile: 'Mensual', annuale: 'Anual' },
    dueMesi: '2 meses gratis',
    alMese: '/mes',
    fatturato: 'facturados una vez al año',
    risparmi: 'ahorras',
    piani: [
      { id: 'starter', nome: 'Starter', prezzo: 69, riga: 'Hasta 500 pedidos al mes.', voci: ['Todas las herramientas incluidas', 'Todas las integraciones', '2 personas del equipo', 'Soporte por email en menos de 48 horas'], cta: 'Empieza con Starter' },
      { id: 'growth', nome: 'Growth', prezzo: 149, riga: 'De 500 a 2.000 pedidos al mes.', voci: ['Todas las herramientas incluidas', 'Todas las integraciones', '5 personas del equipo', 'Soporte prioritario en menos de 12 horas'], cta: 'Empieza con Growth', forte: 'El más elegido' },
      { id: 'scale', nome: 'Scale', prezzo: 299, riga: 'De 2.000 a 7.000 pedidos al mes.', voci: ['Todas las herramientas incluidas', 'Todas las integraciones', 'Personas del equipo ilimitadas', 'Una persona dedicada a ti'], cta: 'Empieza con Scale' },
      { id: 'enterprise', nome: 'Enterprise', prezzo: 599, riga: 'Más de 7.000 pedidos al mes.', voci: ['Todas las herramientas incluidas', 'Integraciones a medida', 'Puesta en marcha con nosotros, con SLA', 'Un account manager dedicado'], cta: 'Empieza con Enterprise' },
    ],
  },
  domande: {
    etichetta: 'Preguntas',
    titolo: 'Lo que pregunta quien empieza.',
    voci: [
      { q: '¿Cómo llega LyftAI a conocer mi marca?', a: 'En la sección Brand Identity escribes quién eres, a quién vendes, cómo hablas y lo que nunca se debe decir. La IA vuelve a leer esta información en cada respuesta.' },
      { q: '¿De dónde salen los números?', a: 'De las plataformas que conectas: Shopify para pedidos, IVA y clientes; Meta y Google para el gasto; GA4 y Search Console para el tráfico. Cada número indica de qué fuente viene.' },
      { q: 'También vendo en marketplaces o en tienda física. ¿Funciona igual?', a: 'Sí. Las ventas de marketplaces y tiendas físicas se quedan fuera de las cuentas de la publicidad, así el MER y el coste por cliente siguen limpios. En la cuenta de resultados, en cambio, sí están.' },
      { q: '¿Mis datos están seguros?', a: 'Cada empresa tiene sus propias credenciales y sus propios datos, separados de los de las demás. Las conexiones están cifradas y los datos nunca se comparten entre clientes.' },
      { q: '¿Cuánto se tarda en empezar?', a: 'Pocos minutos. Conectas Shopify, Meta, Google y tu herramienta de email con un clic, sin copiar claves. Los primeros números llegan mientras terminas.' },
      { q: '¿Cómo funciona la prueba gratuita?', a: '14 días con todo incluido, sin tarjeta. Al final eliges un plan, o lo dejas.' },
      { q: '¿Puedo cancelar cuando quiera?', a: 'Sí. Cancelas desde el portal de pagos, en cualquier momento y sin penalizaciones.' },
      { q: '¿Cumplís con el RGPD?', a: 'Sí. El DPA está disponible, puedes exportar o borrar la cuenta tú mismo y los proveedores que tratan los datos aparecen en la política de privacidad.' },
    ],
  },
  contatti: {
    etichetta: 'Hablemos',
    titolo: '¿Quieres verlo con tus datos?',
    sotto: 'Escríbenos y te respondemos en menos de 24 horas. Sin comerciales: respondemos nosotros.',
    nome: 'Nombre y apellidos', nomeEsempio: 'Lucía García',
    azienda: 'Empresa', aziendaEsempio: 'Acme S.L.',
    email: 'Email', emailEsempio: 'lucia@acme.es',
    telefono: 'Teléfono', telefonoEsempio: '+34 612 345 678',
    sito: 'Sitio web', sitoEsempio: 'https://acme.es',
    fatturatoAnnuo: 'Facturación anual', scegli: 'Elige',
    messaggio: 'Mensaje', messaggioEsempio: '¿En qué plataformas vendes y qué te gustaría entender mejor?',
    richiesti: 'Necesitamos al menos nombre, empresa y email.',
    invia: 'Enviar',
    invio: 'Enviando…',
    fattoTitolo: 'Mensaje recibido.',
    fattoTesto: 'Te respondemos por email en menos de 24 horas.',
    avvertenza: 'Los datos van a LYFT SRL y solo sirven para responderte. Sin newsletter.',
  },
  chiusura: {
    titolo: 'Deja de adivinar.',
    sotto: 'Conecta tu tienda y en pocos minutos tienes tus números, bien ordenados.',
    prova: 'Prueba 14 días gratis',
    demo: 'Ver la demo',
  },
  piede: {
    tagline: 'Los números de tu e-commerce, en un solo sitio.',
    prodotto: 'Producto', azienda: 'Empresa', legale: 'Aviso legal',
    privacy: 'Privacidad', termini: 'Términos del servicio', dpa: 'Tratamiento de datos (DPA)',
    diritti: 'Todos los derechos reservados.',
  },
}

const fr = {
  nav: {
    prodotto: 'Produit', agenzie: 'Agences', prezzi: 'Tarifs', domande: 'Questions',
    accedi: 'Connexion', prova: 'Essai gratuit', menu: 'Menu', lingua: 'Langue', tema: 'Thème', giorno: 'Mode clair', notte: 'Mode sombre',
  },
  apertura: {
    etichetta: 'Pour les boutiques Shopify',
    titolo: 'Ce que vous vendez, ce que vous dépensez, ce qu’il vous reste.',
    // Il titolo a macchina da scrivere: «Ce que vous» resta, il resto si scrive e si cancella a turno.
    titoloPrima: 'Ce que vous ', oggetti: ['vendez, heure par heure.', 'dépensez sur Meta et Google.', 'gardez sur chaque produit.', 'gardez sur chaque client.'],
    sotto: 'LyftAI réunit Shopify, Meta, Google et vos emails au même endroit, avec des comptes à jour pendant que vous vendez. Et vous dit quoi faire ensuite.',
    prova: 'Essai gratuit de 14 jours',
    demo: 'Voir la démo',
    promesse: ['Aucune carte demandée', 'Connecté en quelques minutes', 'En cinq langues'],
    alt: 'Le Dashboard de LyftAI : chiffre d’affaires, dépenses publicitaires et MER comparés à la période précédente, et les visiteurs en temps réel sur le globe',
    globo: { sessioni: 'Sur le site en ce moment', ordini: 'Commandes aujourd’hui', nuovo: 'Nouvelle commande', nota: 'Boutique d’exemple, données simulées' },
  },
  fonti: { etichetta: 'Lit les données de' },
  blocchi: [
    {
      id: 'productPerformance',
      etichetta: 'Performance produits',
      titolo: 'La vraie marge de chaque produit.',
      testo: 'Sur chaque vente, nous retirons la TVA, le coût du produit et la publicité qui lui revient. Ce qui reste, c’est la marge, ligne par ligne.',
      punti: [
        ['TVA lue dans Shopify,', 'produit par produit, au taux que vous avez défini dans votre boutique.'],
        ['Publicité attribuée par le lien de l’annonce :', 'la campagne qui mène à un produit pèse sur ce produit ; le reste est réparti selon le chiffre d’affaires.'],
        ['Coût par variante, avec l’historique :', 'si le fournisseur change de prix, les mois passés restent justes.'],
      ],
      alt: 'Tableau Performance produits : ventes, TVA, net, coût, publicité et marge de chaque produit',
    },
    {
      id: 'kpiBrain',
      etichetta: 'KPI Brain',
      titolo: 'La publicité, mesurée sur les vraies commandes.',
      testo: 'MER, coût par commande et coût par nouveau client, calculés sur les dépenses Meta et Google et sur les commandes Shopify. Pas sur ce que les plateformes disent avoir vendu.',
      punti: [
        ['Aujourd’hui contre hier, à la même heure :', 'à 11 h, vous comparez avec 11 h hier, pas avec la journée entière.'],
        ['D’où vient chaque chiffre :', 'survolez-le pour voir sa source et comment il est calculé.'],
        ['Meta et Google côte à côte :', 'dépenses, ROAS, usure des créations et où déplacer le budget.'],
      ],
      alt: 'KPI Brain : chiffre d’affaires, MER, coût par client, dépenses totales et LTV, avec la source de chaque chiffre',
    },
    {
      id: 'incrContribution',
      etichetta: 'Incrémentalité',
      titolo: 'Ce que chaque canal vend vraiment.',
      testo: 'Une partie des ventes que Meta et Google s’attribuent serait arrivée de toute façon. LyftAI estime ce que chaque canal ajoute vraiment, et où le prochain euro rapporte le plus.',
      punti: [
        ['Contribution et courbes de réponse :', 'vous voyez quand un canal commence à saturer.'],
        ['Simulateur de budget :', 'vous déplacez les dépenses et regardez l’effet prévu sur le chiffre d’affaires.'],
        ['Geo-lift par région :', 'pour le vérifier sur le terrain, avec des régions test et témoin choisies à partir de vos ventes Shopify.'],
      ],
      alt: 'Contribution incrémentale de Meta et Google par rapport aux ventes qui arrivent de toute façon',
    },
    {
      id: 'clienti',
      etichetta: 'Clients',
      titolo: 'Qui revient, et qui est sur le point de partir.',
      testo: 'Vos clients regroupés selon leur façon d’acheter : nouveaux, fidèles, à risque, dormants. Pour chaque groupe, vous savez ce qu’il vaut et vous préparez la bonne campagne en un clic.',
      punti: [
        ['LTV brute et nette :', 'ce que vaut un client après les coûts, pas seulement le chiffre d’affaires qu’il apporte.'],
        ['Cohortes par mois :', 'combien de clients de chaque mois reviennent acheter, et au bout de combien de temps.'],
        ['Email marketing :', 'Klaviyo, Mailchimp ou Omnisend, avec campagnes, flux et chiffre d’affaires au même endroit.'],
      ],
      alt: 'Clients répartis en segments avec valeur, commandes moyennes, jours entre les commandes et ventes totales',
    },
    {
      id: 'pnl',
      etichetta: 'Comptes et rapports',
      titolo: 'Les comptes du mois, jusqu’à l’EBIT.',
      testo: 'Chiffre d’affaires net, coût des ventes, publicité et les dépenses que vous saisissez : le compte de résultat se construit tout seul, mois par mois, avec l’évolution par rapport au mois précédent.',
      punti: [
        ['Registre quotidien des ventes pour votre comptable :', 'ventes par jour et par pays, avec la TVA enregistrée par Shopify, dans un fichier Excel.'],
        ['Rapports PDF :', 'semaine, mois, trimestre et année, dans la langue de celui qui les lit.'],
        ['Le film de la semaine :', 'les chiffres de la semaine l’un après l’autre, à regarder plutôt qu’à lire.'],
      ],
      alt: 'Compte de résultat mensuel avec chiffre d’affaires, coûts et EBIT',
    },
  ],
  ai: {
    etichetta: 'Le Cerveau',
    titolo: 'Une IA qui connaît votre boutique.',
    sotto: 'Vous lui présentez votre marque une fois : produits, clients, ton de voix. Ensuite, elle répond avec vos chiffres, pas avec des conseils valables pour tout le monde.',
    voci: [
      { titolo: 'Demandez, elle répond avec les données', testo: '« Pourquoi la marge a-t-elle baissé cette semaine ? » Elle lit Shopify, Meta et Google et vous dit ce qui a changé.' },
      { titolo: 'Le briefing du matin', testo: 'Ce qui s’est passé hier et ce qu’il faut regarder aujourd’hui, avant même d’ouvrir les tableaux.' },
      { titolo: 'Une équipe pour chaque domaine', testo: 'Des agents dédiés à la publicité, au SEO, au site et aux chiffres, qui travaillent tous sur les mêmes données.' },
    ],
    chat: {
      negozio: 'boutique démo', scrive: 'en train d’écrire…',
      scambi: [
        { d: 'Pourquoi la marge a-t-elle baissé cette semaine ?', r: 'Elle a perdu 2,4 points, pour deux raisons : sur Meta, la campagne « Prospecting – Video » amène de nouveaux clients à €41 chacun, contre €29 le mois dernier ; et les Scarpe Running AirFlow se sont surtout vendues en promotion. Je déplacerais €40 par jour vers le retargeting du catalogue, qui rapporte 4,1× en ce moment.' },
        { d: 'Quels produits pousser sur Google ?', r: 'Borsone Duffel 40L, Felpa Hoodie Essential et Guanti Training Grip : ensemble, ils font 22 % de la marge mais ne prennent que 6 % des dépenses Google. Ce sont les trois premiers à mettre dans une campagne dédiée.' },
        { d: 'Où en est-on aujourd’hui ?', r: 'À 11 h, vous êtes à €2 140, 12 % de plus qu’hier à la même heure. MER 3,6×. Les commandes viennent surtout de Milan et de Rome ; rien d’anormal sur Meta ni sur Google.' },
      ],
    },
  },
  tutto: {
    etichetta: 'Tout inclus',
    titolo: 'Chaque outil, dans chaque offre.',
    sotto: 'Le prix augmente avec vos commandes, jamais avec les fonctionnalités.',
    aree: [
      { icona: 'grid', titolo: 'Ventes', voci: ['Dashboard et salle de contrôle', 'Inventaire et tailles épuisées', 'Performance et coûts produit', 'LTV et cohortes'] },
      { icona: 'target', titolo: 'Meta', voci: ['KPI et détail par annonce', 'Créations et leur usure', 'Conseils sur le budget', 'Campagnes de leads'] },
      { icona: 'search', titolo: 'Google', voci: ['KPI et détail des campagnes', 'Produits et verdicts', 'Conseils sur le budget'] },
      { icona: 'layers', titolo: 'Incrémentalité', voci: ['Contribution incrémentale', 'Courbes de réponse', 'Simulateur de budget', 'Geo-lift'] },
      { icona: 'users', titolo: 'Clients et email', voci: ['Segments par comportement', 'Idées de campagne avec l’IA', 'Klaviyo, Mailchimp, Omnisend'] },
      { icona: 'scan', titolo: 'Site et SEO', voci: ['Audit SEO et Search Console', 'Mots-clés et visibilité dans les IA', 'Conversions et analyse du site'] },
      { icona: 'euro', titolo: 'Comptes et rapports', voci: ['Compte de résultat', 'Registre quotidien des ventes', 'Rapports hebdomadaires, mensuels, trimestriels, annuels', 'Simulateur du compte de résultat'] },
      { icona: 'kanban', titolo: 'Travail d’équipe', voci: ['Projets et tâches', 'Calendrier, congés et absences', 'Lyftimer, les heures de travail', 'LyftTalk, le chat de l’équipe'] },
    ],
    rivenditori: {
      titolo: 'Si vous vendez plusieurs marques',
      testo: 'Prix de la concurrence, marques les plus vendues, et ventes marketplace et en magasin tenues à l’écart des chiffres de la publicité. Ces fonctions ne s’activent que pour ceux qui en ont besoin.',
    },
  },
  agenzie: {
    etichetta: 'Pour les agences et les freelances',
    titolo: 'Tous vos clients, un seul accès.',
    sotto: 'Un espace séparé pour chaque client, avec ses données et ses intégrations. Vous passez de l’un à l’autre en un clic.',
    voci: [
      { titolo: 'Données séparées', testo: 'Chaque client ne voit que ses données. Vous, vous voyez tout.' },
      { titolo: 'Cinq langues', testo: 'Italien, anglais, espagnol, français et allemand, y compris dans les rapports PDF.' },
      { titolo: 'Prix selon le nombre de clients', testo: 'Tous les outils inclus : vous payez selon le nombre d’entreprises que vous gérez.' },
    ],
    cta: 'Voir les offres pour agences',
  },
  prezzi: {
    etichetta: 'Tarifs',
    titolo: 'Vous payez selon votre taille. Tous les outils sont là.',
    sotto: '14 jours gratuits, sans carte. Résiliez quand vous voulez.',
    garanzia: 'La bonne offre, ce sont vos vraies commandes Shopify qui la décident : vous passez à l’offre supérieure seulement quand vous grandissez vraiment.',
    founder: 'Founder : −30 % à vie pour les 100 premières entreprises, y compris sur l’offre annuelle.',
    pubblico: { brand: 'Entreprises', agenzie: 'Agences et freelances' },
    agenzieSotto: 'Gérez tous vos clients depuis un seul endroit. Vous payez selon le nombre d’entreprises et passez de l’une à l’autre en un clic.',
    cadenza: { mensile: 'Mensuel', annuale: 'Annuel' },
    dueMesi: '2 mois offerts',
    alMese: '/mois',
    fatturato: 'facturés une fois par an',
    risparmi: 'vous économisez',
    piani: [
      { id: 'starter', nome: 'Starter', prezzo: 69, riga: 'Jusqu’à 500 commandes par mois.', voci: ['Tous les outils inclus', 'Toutes les intégrations', '2 membres de l’équipe', 'Support par email sous 48 heures'], cta: 'Commencer avec Starter' },
      { id: 'growth', nome: 'Growth', prezzo: 149, riga: 'De 500 à 2 000 commandes par mois.', voci: ['Tous les outils inclus', 'Toutes les intégrations', '5 membres de l’équipe', 'Support prioritaire sous 12 heures'], cta: 'Commencer avec Growth', forte: 'Le plus choisi' },
      { id: 'scale', nome: 'Scale', prezzo: 299, riga: 'De 2 000 à 7 000 commandes par mois.', voci: ['Tous les outils inclus', 'Toutes les intégrations', 'Membres de l’équipe illimités', 'Une personne dédiée à vous'], cta: 'Commencer avec Scale' },
      { id: 'enterprise', nome: 'Enterprise', prezzo: 599, riga: 'Plus de 7 000 commandes par mois.', voci: ['Tous les outils inclus', 'Intégrations sur mesure', 'Démarrage accompagné par nous, avec SLA', 'Un account manager dédié'], cta: 'Commencer avec Enterprise' },
    ],
  },
  domande: {
    etichetta: 'Questions',
    titolo: 'Les questions de ceux qui débutent.',
    voci: [
      { q: 'Comment LyftAI connaît-il ma marque ?', a: 'Dans la section Brand Identity, vous écrivez qui vous êtes, à qui vous vendez, comment vous parlez et ce qu’il ne faut jamais dire. L’IA relit ces informations à chaque réponse.' },
      { q: 'D’où viennent les chiffres ?', a: 'Des plateformes que vous connectez : Shopify pour les commandes, la TVA et les clients ; Meta et Google pour les dépenses ; GA4 et Search Console pour le trafic. Chaque chiffre indique sa source.' },
      { q: 'Je vends aussi sur des marketplaces ou en magasin. Ça fonctionne quand même ?', a: 'Oui. Les ventes marketplace et en magasin restent en dehors des chiffres de la publicité, pour que le MER et le coût par client restent propres. Dans le compte de résultat, en revanche, elles sont bien là.' },
      { q: 'Mes données sont-elles en sécurité ?', a: 'Chaque entreprise a ses propres identifiants et ses propres données, séparés de ceux des autres. Les connexions sont chiffrées et les données ne sont jamais partagées entre clients.' },
      { q: 'Combien de temps faut-il pour démarrer ?', a: 'Quelques minutes. Vous connectez Shopify, Meta, Google et votre outil d’emailing en un clic, sans copier de clés. Les premiers chiffres arrivent pendant que vous terminez.' },
      { q: 'Comment fonctionne l’essai gratuit ?', a: '14 jours avec tout inclus, sans carte. À la fin, vous choisissez une offre, ou vous en restez là.' },
      { q: 'Puis-je résilier quand je veux ?', a: 'Oui. Vous résiliez depuis le portail de paiement, à tout moment et sans pénalités.' },
      { q: 'Êtes-vous conformes au RGPD ?', a: 'Oui. Le DPA est disponible, vous pouvez exporter ou supprimer votre compte vous-même, et les prestataires qui traitent les données sont listés dans la politique de confidentialité.' },
    ],
  },
  contatti: {
    etichetta: 'Parlons-en',
    titolo: 'Vous voulez le voir sur vos données ?',
    sotto: 'Écrivez-nous, nous vous répondons sous 24 heures. Pas de commerciaux : c’est nous qui répondons.',
    nome: 'Nom et prénom', nomeEsempio: 'Marie Dubois',
    azienda: 'Entreprise', aziendaEsempio: 'Acme SAS',
    email: 'Email', emailEsempio: 'marie@acme.fr',
    telefono: 'Téléphone', telefonoEsempio: '+33 6 12 34 56 78',
    sito: 'Site web', sitoEsempio: 'https://acme.fr',
    fatturatoAnnuo: 'Chiffre d’affaires annuel', scegli: 'Choisir',
    messaggio: 'Message', messaggioEsempio: 'Sur quelles plateformes vendez-vous et qu’aimeriez-vous mieux comprendre ?',
    richiesti: 'Il nous faut au moins le nom, l’entreprise et l’email.',
    invia: 'Envoyer',
    invio: 'Envoi…',
    fattoTitolo: 'Message reçu.',
    fattoTesto: 'Nous vous répondons par email sous 24 heures.',
    avvertenza: 'Vos données vont à LYFT SRL et servent uniquement à vous répondre. Pas de newsletter.',
  },
  chiusura: {
    titolo: 'Arrêtez de deviner.',
    sotto: 'Connectez votre boutique et, en quelques minutes, vos chiffres sont là, bien en ordre.',
    prova: 'Essai gratuit de 14 jours',
    demo: 'Voir la démo',
  },
  piede: {
    tagline: 'Les chiffres de votre e-commerce, au même endroit.',
    prodotto: 'Produit', azienda: 'Entreprise', legale: 'Mentions légales',
    privacy: 'Confidentialité', termini: 'Conditions d’utilisation', dpa: 'Traitement des données (DPA)',
    diritti: 'Tous droits réservés.',
  },
}

const de = {
  nav: {
    prodotto: 'Produkt', agenzie: 'Agenturen', prezzi: 'Preise', domande: 'Fragen',
    accedi: 'Anmelden', prova: 'Kostenlos testen', menu: 'Menü', lingua: 'Sprache', tema: 'Design', giorno: 'Heller Modus', notte: 'Dunkler Modus',
  },
  apertura: {
    etichetta: 'Für Shopify-Shops',
    titolo: 'Was du verkaufst, was du ausgibst, was dir bleibt.',
    // Il titolo a macchina da scrivere: «Was du» resta, il resto si scrive e si cancella a turno.
    titoloPrima: 'Was du ', oggetti: ['verkaufst, Stunde für Stunde.', 'für Meta und Google ausgibst.', 'an jedem Produkt verdienst.', 'an jedem Kunden verdienst.'],
    sotto: 'LyftAI bringt Shopify, Meta, Google und deine E-Mails an einem Ort zusammen, laufend aktuell, während du verkaufst. Und sagt dir, was als Nächstes zu tun ist.',
    prova: '14 Tage kostenlos testen',
    demo: 'Demo ansehen',
    promesse: ['Keine Kreditkarte nötig', 'In wenigen Minuten verbunden', 'In fünf Sprachen'],
    alt: 'Das LyftAI-Dashboard: Umsatz, Werbeausgaben und MER im Vergleich zum Vorzeitraum, dazu die Besucher in Echtzeit auf dem Globus',
    globo: { sessioni: 'Gerade im Shop', ordini: 'Bestellungen heute', nuovo: 'Neue Bestellung', nota: 'Beispielshop, simulierte Daten' },
  },
  fonti: { etichetta: 'Liest die Daten aus' },
  blocchi: [
    {
      id: 'productPerformance',
      etichetta: 'Produkt-Performance',
      titolo: 'Die echte Marge jedes Produkts.',
      testo: 'Vom Umsatz ziehen wir die MwSt., die Produktkosten und den Anteil der Werbung ab, der auf das Produkt entfällt. Was bleibt, ist die Marge, Zeile für Zeile.',
      punti: [
        ['MwSt. aus Shopify,', 'Produkt für Produkt, mit dem Satz, den du im Shop hinterlegt hast.'],
        ['Werbung zugeordnet über den Link der Anzeige:', 'die Kampagne, die zu einem Produkt führt, zählt für dieses Produkt; der Rest wird nach Umsatz verteilt.'],
        ['Kosten pro Variante, mit Verlauf:', 'wenn der Lieferant den Preis ändert, bleiben die vergangenen Monate korrekt.'],
      ],
      alt: 'Tabelle Produkt-Performance: Umsatz, MwSt., netto, Kosten, Werbung und Marge für jedes Produkt',
    },
    {
      id: 'kpiBrain',
      etichetta: 'KPI Brain',
      titolo: 'Werbung, gemessen an echten Bestellungen.',
      testo: 'MER, Kosten pro Bestellung und Kosten pro Neukunde, berechnet aus den Ausgaben bei Meta und Google und den Bestellungen in Shopify. Nicht aus dem, was die Plattformen als verkauft melden.',
      punti: [
        ['Heute gegen gestern, zur selben Uhrzeit:', 'um 11 Uhr vergleichst du mit gestern 11 Uhr, nicht mit dem ganzen Tag.'],
        ['Woher jede Zahl kommt:', 'fahr mit der Maus darüber und du siehst die Quelle und wie sie berechnet wird.'],
        ['Meta und Google nebeneinander:', 'Ausgaben, ROAS, Ermüdung der Creatives und wohin das Budget gehen sollte.'],
      ],
      alt: 'KPI Brain: Umsatz, MER, Kosten pro Kunde, Gesamtausgaben und LTV, mit der Quelle jeder Zahl',
    },
    {
      id: 'incrContribution',
      etichetta: 'Inkrementalität',
      titolo: 'Was jeder Kanal wirklich verkauft.',
      testo: 'Ein Teil der Verkäufe, die sich Meta und Google zuschreiben, wäre ohnehin gekommen. LyftAI schätzt, was jeder Kanal wirklich beiträgt und wo der nächste Euro am meisten bringt.',
      punti: [
        ['Beitrag und Reaktionskurven:', 'du siehst, wann ein Kanal an seine Sättigung kommt.'],
        ['Budget-Simulator:', 'du verschiebst Ausgaben und siehst die erwartete Wirkung auf den Umsatz.'],
        ['Geo-Lift nach Regionen:', 'für den Test in der Praxis, mit Test- und Kontrollregionen, ausgewählt anhand deiner Shopify-Verkäufe.'],
      ],
      alt: 'Inkrementeller Beitrag von Meta und Google im Vergleich zu den Verkäufen, die ohnehin kommen',
    },
    {
      id: 'clienti',
      etichetta: 'Kunden',
      titolo: 'Wer wiederkommt und wer bald abspringt.',
      testo: 'Deine Kunden, gruppiert nach ihrem Kaufverhalten: neu, treu, gefährdet, inaktiv. Für jede Gruppe weißt du, was sie wert ist, und bereitest mit einem Klick die passende Kampagne vor.',
      punti: [
        ['Brutto- und Netto-LTV:', 'was ein Kunde nach Kosten wert ist, nicht nur wie viel Umsatz er bringt.'],
        ['Kohorten nach Monat:', 'wie viele Kunden jedes Monats wieder kaufen, und nach wie langer Zeit.'],
        ['E-Mail-Marketing:', 'Klaviyo, Mailchimp oder Omnisend, mit Kampagnen, Flows und Umsatz an einem Ort.'],
      ],
      alt: 'Kunden in Segmenten mit Wert, durchschnittlichen Bestellungen, Tagen zwischen Bestellungen und Gesamtumsatz',
    },
    {
      id: 'pnl',
      etichetta: 'Finanzen und Reports',
      titolo: 'Die Zahlen des Monats, bis zum EBIT.',
      testo: 'Nettoumsatz, Wareneinsatz, Werbung und die Ausgaben, die du selbst einträgst: Die GuV baut sich von allein auf, Monat für Monat, mit der Veränderung zum Vormonat.',
      punti: [
        ['Tägliches Umsatzjournal für deinen Steuerberater:', 'Verkäufe nach Tag und Land, mit der von Shopify erfassten MwSt., als Excel-Datei.'],
        ['PDF-Reports:', 'Woche, Monat, Quartal und Jahr, in der Sprache ihrer Leser.'],
        ['Der Film der Woche:', 'die Zahlen der Woche nacheinander, zum Anschauen statt zum Lesen.'],
      ],
      alt: 'Monatliche Gewinn- und Verlustrechnung mit Umsatz, Kosten und EBIT',
    },
  ],
  ai: {
    etichetta: 'Das Gehirn',
    titolo: 'Eine KI, die deinen Shop kennt.',
    sotto: 'Du erzählst ihr einmal von deiner Marke: Produkte, Kunden, Tonalität. Ab dann antwortet sie mit deinen Zahlen, nicht mit Ratschlägen, die für alle passen.',
    voci: [
      { titolo: 'Frag, und sie antwortet mit Daten', testo: '„Warum ist die Marge diese Woche gesunken?“ Sie liest Shopify, Meta und Google und sagt dir, was sich geändert hat.' },
      { titolo: 'Das Morgen-Briefing', testo: 'Was gestern passiert ist und worauf du heute achten solltest, noch bevor du die Tabellen öffnest.' },
      { titolo: 'Ein Team für jeden Bereich', testo: 'Agenten für Werbung, SEO, Website und Zahlen, die alle mit denselben Daten arbeiten.' },
    ],
    chat: {
      negozio: 'Demo-Shop', scrive: 'schreibt…',
      scambi: [
        { d: 'Warum ist die Marge diese Woche gesunken?', r: 'Sie ist um 2,4 Punkte gefallen, aus zwei Gründen: Auf Meta bringt die Kampagne „Prospecting – Video“ Neukunden für €41 pro Kopf, im Vormonat waren es €29; und die Scarpe Running AirFlow wurden vor allem rabattiert verkauft. Ich würde €40 pro Tag ins Katalog-Retargeting verschieben, das gerade 4,1× bringt.' },
        { d: 'Welche Produkte sollten wir auf Google pushen?', r: 'Borsone Duffel 40L, Felpa Hoodie Essential und Guanti Training Grip: Zusammen machen sie 22 % der Marge aus, bekommen aber nur 6 % des Google-Budgets. Sie gehören als Erste in eine eigene Kampagne.' },
        { d: 'Wie läuft es heute?', r: 'Um 11 Uhr stehst du bei €2.140, 12 % über gestern zur selben Uhrzeit. MER 3,6×. Die Bestellungen kommen vor allem aus Mailand und Rom; nichts Auffälliges bei Meta und Google.' },
      ],
    },
  },
  tutto: {
    etichetta: 'Alles inklusive',
    titolo: 'Jedes Tool, in jedem Tarif.',
    sotto: 'Der Preis wächst mit deinen Bestellungen, nie mit den Funktionen.',
    aree: [
      { icona: 'grid', titolo: 'Verkauf', voci: ['Dashboard und Kontrollraum', 'Lagerbestand und ausverkaufte Größen', 'Produkt-Performance und -kosten', 'LTV und Kohorten'] },
      { icona: 'target', titolo: 'Meta', voci: ['KPIs und Details pro Anzeige', 'Creatives und ihre Ermüdung', 'Budget-Empfehlungen', 'Lead-Kampagnen'] },
      { icona: 'search', titolo: 'Google', voci: ['KPIs und Kampagnendetails', 'Produkte und Urteile', 'Budget-Empfehlungen'] },
      { icona: 'layers', titolo: 'Inkrementalität', voci: ['Inkrementeller Beitrag', 'Reaktionskurven', 'Budget-Simulator', 'Geo-Lift'] },
      { icona: 'users', titolo: 'Kunden und E-Mail', voci: ['Segmente nach Verhalten', 'Kampagnenideen mit KI', 'Klaviyo, Mailchimp, Omnisend'] },
      { icona: 'scan', titolo: 'Website und SEO', voci: ['SEO-Audit und Search Console', 'Keywords und Sichtbarkeit in KI-Antworten', 'Conversions und Website-Scan'] },
      { icona: 'euro', titolo: 'Finanzen und Reports', voci: ['Gewinn- und Verlustrechnung', 'Tägliches Umsatzjournal', 'Reports für Woche, Monat, Quartal, Jahr', 'GuV-Simulator'] },
      { icona: 'kanban', titolo: 'Teamarbeit', voci: ['Projekte und Aufgaben', 'Kalender, Urlaub und Abwesenheiten', 'Lyftimer, die Arbeitszeit', 'LyftTalk, der Team-Chat'] },
    ],
    rivenditori: {
      titolo: 'Wenn du mehrere Marken verkaufst',
      testo: 'Preise der Konkurrenz, meistverkaufte Marken, und Verkäufe über Marktplätze und Ladengeschäfte, die aus den Werbezahlen herausgehalten werden. Das wird nur für die aktiviert, die es brauchen.',
    },
  },
  agenzie: {
    etichetta: 'Für Agenturen und Freelancer',
    titolo: 'Alle Kunden, ein Zugang.',
    sotto: 'Ein eigener Bereich für jeden Kunden, mit seinen Daten und Integrationen. Du wechselst mit einem Klick von einem zum anderen.',
    voci: [
      { titolo: 'Getrennte Daten', testo: 'Jeder Kunde sieht nur seine eigenen. Du siehst alle.' },
      { titolo: 'Fünf Sprachen', testo: 'Italienisch, Englisch, Spanisch, Französisch und Deutsch, auch in den PDF-Reports.' },
      { titolo: 'Preis nach Anzahl der Kunden', testo: 'Alle Tools inklusive: Du zahlst danach, wie viele Unternehmen du betreust.' },
    ],
    cta: 'Tarife für Agenturen ansehen',
  },
  prezzi: {
    etichetta: 'Preise',
    titolo: 'Du zahlst nach deiner Größe. Alle Tools sind dabei.',
    sotto: '14 Tage kostenlos, ohne Karte. Jederzeit kündbar.',
    garanzia: 'Den passenden Tarif bestimmen deine echten Shopify-Bestellungen: Du steigst erst auf, wenn du wirklich wächst.',
    founder: 'Founder: −30 % auf Lebenszeit für die ersten 100 Unternehmen, auch im Jahrestarif.',
    pubblico: { brand: 'Unternehmen', agenzie: 'Agenturen und Freelancer' },
    agenzieSotto: 'Verwalte alle Kunden an einem Ort. Du zahlst nach Anzahl der Unternehmen und wechselst mit einem Klick zwischen ihnen.',
    cadenza: { mensile: 'Monatlich', annuale: 'Jährlich' },
    dueMesi: '2 Monate gratis',
    alMese: '/Monat',
    fatturato: 'einmal im Jahr abgerechnet',
    risparmi: 'du sparst',
    piani: [
      { id: 'starter', nome: 'Starter', prezzo: 69, riga: 'Bis zu 500 Bestellungen im Monat.', voci: ['Alle Tools inklusive', 'Alle Integrationen', '2 Teammitglieder', 'E-Mail-Support innerhalb von 48 Stunden'], cta: 'Mit Starter beginnen' },
      { id: 'growth', nome: 'Growth', prezzo: 149, riga: 'Von 500 bis 2.000 Bestellungen im Monat.', voci: ['Alle Tools inklusive', 'Alle Integrationen', '5 Teammitglieder', 'Bevorzugter Support innerhalb von 12 Stunden'], cta: 'Mit Growth beginnen', forte: 'Am häufigsten gewählt' },
      { id: 'scale', nome: 'Scale', prezzo: 299, riga: 'Von 2.000 bis 7.000 Bestellungen im Monat.', voci: ['Alle Tools inklusive', 'Alle Integrationen', 'Unbegrenzt viele Teammitglieder', 'Eine feste Ansprechperson für dich'], cta: 'Mit Scale beginnen' },
      { id: 'enterprise', nome: 'Enterprise', prezzo: 599, riga: 'Über 7.000 Bestellungen im Monat.', voci: ['Alle Tools inklusive', 'Individuelle Integrationen', 'Einrichtung durch uns, mit SLA', 'Ein eigener Account Manager'], cta: 'Mit Enterprise beginnen' },
    ],
  },
  domande: {
    etichetta: 'Fragen',
    titolo: 'Was man am Anfang fragt.',
    voci: [
      { q: 'Wie lernt LyftAI meine Marke kennen?', a: 'Im Bereich Brand Identity schreibst du, wer du bist, an wen du verkaufst, wie du sprichst und was nie gesagt werden darf. Die KI liest diese Angaben bei jeder Antwort erneut.' },
      { q: 'Woher kommen die Zahlen?', a: 'Von den Plattformen, die du verbindest: Shopify für Bestellungen, MwSt. und Kunden; Meta und Google für die Ausgaben; GA4 und Search Console für den Traffic. Jede Zahl zeigt, aus welcher Quelle sie stammt.' },
      { q: 'Ich verkaufe auch über Marktplätze oder im Laden. Funktioniert das trotzdem?', a: 'Ja. Verkäufe über Marktplätze und Ladengeschäfte bleiben aus den Werbezahlen heraus, damit MER und Kosten pro Kunde sauber bleiben. In der Gewinn- und Verlustrechnung sind sie dagegen enthalten.' },
      { q: 'Sind meine Daten sicher?', a: 'Jedes Unternehmen hat eigene Zugangsdaten und eigene Daten, getrennt von denen der anderen. Die Verbindungen sind verschlüsselt, und Daten werden nie zwischen Kunden geteilt.' },
      { q: 'Wie lange dauert der Start?', a: 'Ein paar Minuten. Du verbindest Shopify, Meta, Google und dein E-Mail-Tool mit einem Klick, ohne Schlüssel zu kopieren. Die ersten Zahlen kommen, während du fertig wirst.' },
      { q: 'Wie funktioniert die kostenlose Testphase?', a: '14 Tage mit allem inklusive, ohne Karte. Am Ende wählst du einen Tarif, oder du lässt es.' },
      { q: 'Kann ich jederzeit kündigen?', a: 'Ja. Du kündigst im Zahlungsportal, jederzeit und ohne Gebühren.' },
      { q: 'Seid ihr DSGVO-konform?', a: 'Ja. Das DPA ist verfügbar, du kannst dein Konto selbst exportieren oder löschen, und die Dienstleister, die Daten verarbeiten, stehen in der Datenschutzerklärung.' },
    ],
  },
  contatti: {
    etichetta: 'Lass uns reden',
    titolo: 'Willst du es mit deinen Daten sehen?',
    sotto: 'Schreib uns, wir antworten innerhalb von 24 Stunden. Keine Verkäufer: Wir antworten selbst.',
    nome: 'Vor- und Nachname', nomeEsempio: 'Max Müller',
    azienda: 'Unternehmen', aziendaEsempio: 'Acme GmbH',
    email: 'E-Mail', emailEsempio: 'max@acme.de',
    telefono: 'Telefon', telefonoEsempio: '+49 151 23456789',
    sito: 'Website', sitoEsempio: 'https://acme.de',
    fatturatoAnnuo: 'Jahresumsatz', scegli: 'Auswählen',
    messaggio: 'Nachricht', messaggioEsempio: 'Auf welchen Plattformen verkaufst du, und was möchtest du besser verstehen?',
    richiesti: 'Wir brauchen mindestens Name, Unternehmen und E-Mail.',
    invia: 'Senden',
    invio: 'Wird gesendet…',
    fattoTitolo: 'Nachricht angekommen.',
    fattoTesto: 'Wir antworten dir innerhalb von 24 Stunden per E-Mail.',
    avvertenza: 'Deine Daten gehen an LYFT SRL und dienen nur dazu, dir zu antworten. Kein Newsletter.',
  },
  chiusura: {
    titolo: 'Hör auf zu raten.',
    sotto: 'Verbinde deinen Shop, und in wenigen Minuten hast du deine Zahlen, sauber geordnet.',
    prova: '14 Tage kostenlos testen',
    demo: 'Demo ansehen',
  },
  piede: {
    tagline: 'Die Zahlen deines Onlineshops, an einem Ort.',
    prodotto: 'Produkt', azienda: 'Unternehmen', legale: 'Rechtliches',
    privacy: 'Datenschutz', termini: 'Nutzungsbedingungen', dpa: 'Auftragsverarbeitung (DPA)',
    diritti: 'Alle Rechte vorbehalten.',
  },
}

export const TESTI = { it, en, es, fr, de }
export const LINGUE = ['it', 'en', 'es', 'fr', 'de']
